# Generated by Django 6.0.4 on 2026-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='replacement_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times a stored file was superseded by a new upload (citizen replace/re-upload).'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document_type',
            field=models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('indigency', 'Certificate of Indigency'), ('school_id', 'School ID'), ('grade_card', 'Report Card / Grade Card'), ('cert_of_enrollment', 'Certificate of Enrollment/Registration'), ('others', 'Other Supporting Document')], default='others', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='requestdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('request', 'document_type'), name='assistance_requestdocument_active_unique_type'),
        ),
    ]
