# Generated by Django 6.0.4 on 2026-04-26 12:53

from django.db import migrations, models


def normalize_legacy_request_statuses(apps, schema_editor):
    CitizenRequest = apps.get_model("assistance", "CitizenRequest")
    status_map = {
        "pending": "awaiting_documents",
        "review": "under_review",
        "denied": "closed",
    }
    locked_statuses = {"approved", "claimable", "claimed", "closed"}

    for old_status, new_status in status_map.items():
        CitizenRequest.objects.filter(status=old_status).update(status=new_status)

    CitizenRequest.objects.filter(status__in=locked_statuses).update(is_locked=True)
    CitizenRequest.objects.exclude(status__in=locked_statuses).update(is_locked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_requestdocument_softdelete_replace'),
    ]

    operations = [
        migrations.RunPython(
            normalize_legacy_request_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='citizenrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('awaiting_documents', 'Awaiting Documents'), ('under_review', 'Under Review'), ('needs_attention', 'Needs Attention'), ('approved', 'Approved'), ('claimable', 'Ready to Claim'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='submitted', max_length=20),
        ),
    ]
